rmcs_executor:
  ros__parameters:
    update_rate: 1000.0

    components:
      - rmcs_core::hardware::M3508TestHardware -> m3508_hardware
      - rmcs_core::controller::pid::PidController -> task2_pid
      - rmcs_core::debug::Task2Telemetry -> task2_telemetry


m3508_hardware:
  ros__parameters:
    board_serial: ""
    max_velocity: 100.0


task2_pid:
  ros__parameters:
    measurement: /m3508/velocity
    setpoint: /m3508/target_velocity
    control: /m3508/control_torque

    kp: 0.002
    ki: 0.00008
    kd: 0.0

    integral_min: -100.0
    integral_max: 100.0

    integral_split_min: -100.0
    integral_split_max: 100.0

    output_min: -3.0
    output_max: 3.0