rmcs_executor:
  ros__parameters:
    update_rate: 1000.0

    components:
      - rmcs_core::hardware::M6020Task3Hardware -> m6020_hardware
      - rmcs_core::controller::motor::M6020DoublePidController -> task3_pid

m6020_hardware:
  ros__parameters:
    board_serial: ""

task3_pid:
  ros__parameters:
    # 角度外环
    angle_kp: 2.0
    angle_ki: 0.0
    angle_kd: 0.0

    # 速度内环
    velocity_kp: 0.02
    velocity_ki: 0.0
    velocity_kd: 0.0

    # 外环输出：目标速度
    max_velocity: 20.0

    # 角度积分限幅
    angle_integral_min: -1.0
    angle_integral_max: 1.0

    # 速度积分限幅
    velocity_integral_min: -10.0
    velocity_integral_max: 10.0

    # 最终扭矩限幅
    max_torque: 1.0